"""Recommendation models for AI-generated automation plans."""

from typing import Literal

from pydantic import BaseModel, Field

__all__ = [
    "EquipmentPlacement",
    "ExpectedMetrics",
    "Recommendation",
    "WorkflowStep",
    "WorkObject",
]


class EquipmentPlacement(BaseModel):
    """Placement of new equipment in the scene.

    Args:
        equipment_id: ID from the knowledge-base catalog.
        position: 3D position (x, y, z) in meters.
        orientation_deg: Rotation around Z-axis in degrees.
        purpose: Why this equipment is placed here.
        zone: Which zone this equipment belongs to.
    """

    equipment_id: str
    position: tuple[float, float, float]
    orientation_deg: float = 0.0
    purpose: str
    zone: str


class WorkObject(BaseModel):
    """Object to be manipulated during simulation.

    Args:
        name: Object name (e.g. "finished_print", "parcel").
        shape: Primitive shape for MuJoCo geom.
        size: Dimensions — box: (x,y,z), cylinder: (r,h,0), sphere: (r,0,0).
        mass_kg: Object mass in kilograms.
        position: Initial 3D position (x, y, z) in meters.
        count: Number of instances to create.
    """

    name: str
    shape: Literal["box", "cylinder", "sphere"]
    size: tuple[float, float, float]
    mass_kg: float = Field(gt=0)
    position: tuple[float, float, float]
    count: int = Field(default=1, ge=1)


class WorkflowStep(BaseModel):
    """A single step in the automation workflow.

    Args:
        order: Step execution order (1-based).
        action: Action type to perform.
        equipment_id: Equipment performing the action (None for "wait").
        target: Key in target_positions dict for 3D coordinates.
        duration_s: Expected step duration in seconds.
        params: Additional parameters (e.g. conveyor speed).
    """

    order: int = Field(ge=1)
    action: Literal["pick", "place", "move", "transport", "inspect", "wait"]
    equipment_id: str | None = None
    target: str
    duration_s: float = Field(gt=0)
    params: dict[str, float | str] | None = None


class ExpectedMetrics(BaseModel):
    """Expected performance metrics for the automation plan.

    Args:
        cycle_time_s: Expected time for one full cycle.
        throughput_per_hour: Expected items processed per hour.
        notes: Additional notes about expected performance.
    """

    cycle_time_s: float = Field(gt=0)
    throughput_per_hour: float = Field(ge=0)
    notes: str = ""


class Recommendation(BaseModel):
    """Complete automation plan generated by Claude.

    Args:
        equipment: List of equipment placements.
        work_objects: Objects for manipulation in the simulation.
        target_positions: Mapping of target names to 3D coordinates.
        workflow_steps: Ordered list of workflow steps.
        expected_metrics: Expected performance metrics.
        text_plan: Human-readable plan description.
    """

    equipment: list[EquipmentPlacement]
    work_objects: list[WorkObject] = Field(default_factory=list)
    target_positions: dict[str, tuple[float, float, float]]
    workflow_steps: list[WorkflowStep]
    expected_metrics: ExpectedMetrics
    text_plan: str = ""
